version: '3'

services:
    rabbit:
        build:
            context: ./rabbit
        hostname: "rabbit"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"
        labels:
            name: "rabbitmq"

    gateway:
        build:
            context: ./gateway
        environment: 
            ASPNETCORE_URLS: http://+:5000
        ports:
            - "5000:5000"

    