version: '3'

services:

    rabbit:
        build:
            context: ./rabbit
        networks:
            - backend
            - frontend
        env_file:
            - variables.env
        hostname: rabbit
        ports:
            - 15672:15672
            - 5672:5672

    redis:
        build:
            context: ./redis
        hostname: redis
        networks:
            - backend
        ports:
            - 6379:6379
        env_file:
            - variables.env

    # gateway:
    #     build:
    #         context: ./gateway
    #     networks:
    #         - frontend
    #     ports:
    #         - "5000:5000"
    #     env_file:
    #         - variables.env
    #     depends_on:
    #         - rabbit
    
    fit:
        build:
            context: ./pythonService
            dockerfile: DockerfileFit
        networks:
            - backend
        env_file:
            - variables.env
        depends_on:
            - rabbit
            - redis
        deploy:
            replicas: 6

    forecast:
        build:
            context: ./pythonService
            dockerfile: DockerfileForecast
        networks:
            - backend
        env_file:
            - variables.env
        depends_on:
            - rabbit
            - redis
        deploy:
            replicas: 3

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge