version: '3'

services:
    rabbit:
        build:
            context: ./rabbit
        networks:
            - backend
            - frontend
        env_file:
            - variables.env
        hostname: "rabbit"
        ports:
            - "15672:15672"
            - "5672:5672"
        labels:
            name: "rabbit"

    gateway:
        build:
            context: ./gateway
        networks:
            - frontend
        env_file:
            - variables.env
        ports:
            - "5000:5000"
    
    python_service:
        build:
            context: ./pythonService
        networks:
            - backend
        env_file:
            - variables.env

    redis:
        build:
            context: ./redis
        networks:
            - backend
        ports:
            - "6379:6379"
        env_file:
            - variables.env

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge